### PR TITLE
Docker rework

### PR DESCRIPTION
**Pull request by bastienwirtz**
Hi there :wave: 

A lot issue has been raised around the docker container, so ... let's fix them all !

- https://github.com/bastienwirtz/homer/issues/325
- https://github.com/bastienwirtz/homer/issues/261
- https://github.com/bastienwirtz/homer/issues/209
- https://github.com/bastienwirtz/homer/issues/193

**I'm not a docker expert and I'm opening this PR to work with you to improve this, so feel free to share your thought, ideas, ... It will much appreciated.** If some of you are willing to try it, it would be awesome!

Homer is focused on simplicity, and really liked the idea of the container coming preconfigured with just a file to edit to get started. I tried, without success, to achieve that while not using the root user, so I decided to just simplify it and remove the entrypoint. I'm not even sure the `USER`, `GROUP`, `UID`, `GID` is usefull anymore ? **What to you think ?**

So, the only thing I can think of to keep it easy to get started is just to provide a better documentation to get started, or maybe a command to generate the initial asset ? 

This PR also bring a more robust http server (thanks @Kirmy34 !), and a simple way to use homer in a subpath. I kinda grouped all modifications related to docker / hosting as I want to avoid changing it too often (this kind of change may impact users)

While we're a it, I could use some advise on this one : https://github.com/bastienwirtz/homer/issues/347

Thanks a lot :heart:

### CODE REVIEW

**Comment by bastienwirtz** [comment]
cc @ElleshaHackett, @git-noise,  @justsomebody42, @Nold360, @jorge-lavin, @werwolfby, @JuniorJPDJ.

**Comment by bastienwirtz** [comment]
To give you an idea I tried some entrypoint like: 

```sh
#!/bin/sh

# Default assets & exemple configuration installation.
if [[ "${SKIP_ASSETS_INSTALL}" != "1" && ! -f "/www/config.yml" ]]; then
    echo "No configuration found, installing default config & assets"
    [[ ! -w "/www/assets/" ]] || echo "Assets directory not writable" # && exit 1

    while true; do echo n; done | cp -Ri /www/default-assets/* /www/assets/ &> /dev/null
    [[ $? -ne 0 ]] || echo "Fail to copy default assets" # && exit 1
    yes n | cp -i /www/default-assets/config.yml.dist /www/assets/config.yml &> /dev/null
    [[ $? -ne 0 ]] || echo "Fail to copy default config file" # && exit 1
fi

echo "Starting webserver"
lighttpd -D -f /lighttpd.conf
```

But as the user is created at build time, the assets directory will never have the necessary permission to be writable.

**Comment by Nold360** [comment]
> But as the user is created at build time, the assets directory will never have the necessary permission to be writable.

I don't get that. User is created in Dockerfile, so he is in the image. The directory mounted as `/www/assets` should be owned by that user, before starting the container. [eg `fsGroup` in K8s][yea, afaik it's not that easy in plain docker.

Also on K8s we could use a init container to populate `/www/assets`. 

Anyways, why not simply check if there are any files in `/www/assets` and if not, copy the default ones? 


>  I'm not even sure the USER, GROUP, UID, GID is usefull anymore ? 
`UID` & `GID` don't have any real use afaik. We should have `USER` [in best case using UID eg. `USER 1000`] so Kubernetes can determine which user to give access to the PVCs.

**Comment by bastienwirtz** [comment]
Thanks for your reply @Nold360. 

> I don't get that. User is created in Dockerfile, so he is in the image. The directory mounted as /www/assets should be owned by that user, before starting the container

I mean that no matter what you set as env vars, the homer user is defined at build time and will likely not have the right permissions to write into the mounted directory (unless the uid / guid match). 

> Anyways, why not simply check if there are any files in /www/assets and if not, copy the default ones? 

That is the current behavior. It works all the time because the container run as root, which will not longer be the case (the main goal of this PR). So unless the user inside the container (on which you have no control because it's created at build time) match the user on the host, you will have permission problems.

But I might be missing something.

**Comment by Roundaround** [comment]
What all functionality is the web server meant to provide?

Is this something we could do with nginx instead of darkhttpd or lighttpd? I personally use nginx's docker container to deploy React apps all the time with extreme simplicity. This is one such example at its simplest:

```docker
# Build step
FROM node:16 as builder

WORKDIR /app

COPY . .

RUN yarn install
RUN yarn run build


# Serve step
FROM nginx:stable

WORKDIR /usr/share/nginx/html
RUN rm -rf ./*

COPY --from=builder /app/build .

ENTRYPOINT ["nginx", "-g", "daemon off;"]
```

**Comment by bastienwirtz** [comment]
@Roundaround the web server is not the issue, it does not really matters. The point is how to install default assets (to keep the ease of use) without permission issues. But I think I know what to do, I'll push an update soon.

**Comment by bastienwirtz** [comment]
All right, I think this is good to go.

**Pull request merged**
