### PR TITLE
Use gender-neutral terminology

### PR DESCRIPTION
**Pull request by my-flow**
## Description

Use gender-neutral terminology because it's 2020.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] I've read & comply with the [contributing guidelines](https://github.com/bastienwirtz/homer/blob/master/CONTRIBUTING.md)
- [ ] I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers. 
- [ ] I have made corresponding changes the documentation (README.md).
- [x] I've checked my modifications for any breaking changes, especially in the `config.yml` file

### CODE REVIEW

**Review by shamoon — APPROVED** [review]

**Comment by bastienwirtz** [comment]
Hi @my-flow!
Thanks for this contribution, I like this. 
I added that to add a friendly touch to this message (when I see this message, I'm like, "f*** I lost my ssh tunnel"). 
Would `mate` or `buddy` work? (I'm not a native English speaker, not sure about this)

Could be nice to keep this friendly touch, but it's not a big deal of course, we can just remove it if nothing fits.

**Comment by my-flow** [comment]
Hi @bastienwirtz!
I understand your intentions but can't think of a good alternative. For the moment it's best to remove it.

**Comment by shamoon** [comment]
“Friend”? That’s pretty darn neutral imho

**Comment by bastienwirtz** [comment]
Sounds good to me :+1:

**Comment by Senko-Dev** [comment]
I came from TiA, lol. Hi, I guess!

**Comment by tyzbit** [comment]
As was obvious from @Senko-Dev's comment, this PR was featured on the [TumblrInAction subreddit](https://www.reddit.com/r/TumblrInAction/comments/k7bk30/expects_dev_to_replace_slang_with_gender_neutral/).  Although much of it was censored, this PR is still easy to find.  With that in mind, consider these facts:

- A user submitted a PR with justification for the PR to the repository for a small project
- [The top contributor](https://github.com/bastienwirtz/homer/graphs/contributors) to the repository felt like the change was worth making, and merged it into the repository.
- A third party saw this interaction and posted it on TumblrInAction

Any users from TumblrInAction, especially ones that were not previously part of the community for this repo (this includes me), like with a lion's share of open source software, **are welcome to express their opinions on how software is built on this open forum**.  This opinion includes social issues, as software is not removed from preexisting social contexts.

I do want to reiterate that this community was fine with this change before TumblrInAction came along.  Maybe TumblrInAction can convince the community to restore gendered language.  I make no comment on that here.

What I do want to remind everyone that may comment here that they're **coming to a small, open source project charged with opinions on how it should be made, coming from a place of memes and groupthink**.  Please respect the existing community, and be civil.  **This includes respecting the decisions of the existing community**, if they do not wish to change their minds.  I abide by these rules as well.

**Comment by bastienwirtz** [comment]
Wow, I don't really get what TumblrInAction is about, and all the fuzz, but anyway. 
Whatever your interpretation of the word "dude" here, semantically, it target a specific gender. Homer aim to be used be anyone, therefore this PR is a legitimate bugfix.  
Whatever you think it's useless, important, or not, it's an improvement. No matter the size of the contribution, it's very much appreciated. 

As pointed out by @tyzbit, please respect the choice of this community, and if you don't like it, just leave this project alone :)
Thanks.

**Comment by matthewstrasiotto** [comment]
Shoutout to the maintainer & submitter of this PR for keeping an open mind and wanting to make the FOSS community a more inclusive place 🥇 

Also, shout out to @bastienwirtz because I do like a friendly error message 😄

**Pull request closed without merging**
