### PR TITLE
Feature/custom card colors

### PR DESCRIPTION
**Pull request by tpansino**
## Description

This PR adds basic support for customizing the background and text color of individual cards, via the `config.yml`.

This could also probably be implemented by making a custom style sheet, and allowing the `config.yml` to specify CSS classes to apply to each card, but I wanted to keep it simple. Happy to change my implementation if this is preferred.

I also ~didn't update the example configuration, but I'm happy to do that as well if desired.~ Edit: updated the `configuration.md`.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] I read & comply with the [contributing guidelines](https://github.com/bastienwirtz/homer/blob/master/CONTRIBUTING.md)
- [x] I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers. 
- [x] I have made corresponding changes the documentation (README.md).
- [x] I've check my modifications for any breaking change, especially in the `config.yml` file

### CODE REVIEW

**Comment by bastienwirtz** [comment]
Hi @tpansino !
Thanks for your contribution! I like the idea. I just merged the support for custom CSS file by @gabe565 (https://github.com/bastienwirtz/homer/pulls?q=is%3Apr+is%3Aclosed) so I think the CSS class would be better, and provide more flexibility. 
If you are still willing to change the implementation for the CSS class system, go for it! that would be perfect :)

**Comment by tpansino** [comment]
Agreed @bastienwirtz .

I have updated the feature to use custom CSS classes and created a `custom.css.sample` in the `public/` as an example of how to use it. Tested on Firefox and Chromium and it seems to look ok.

I am very much a backend developer :sweat_smile:, so please feel free to make suggestions if my CSS can be improved.

**Review by bastienwirtz — APPROVED** [review]
Well done @tpansino, it looks good!

**Comment by bastienwirtz** [comment]
@tpansino On second look, I simplified a bit the service component: I moved your class to the parent element and removed it from the children. You can target any element from the parent class (example: `body #app .card.green title`) so it's ok to put it only once on the parent élément. You can find the diff here: https://github.com/bastienwirtz/homer/commit/ffe3404a2a9b36d69e880baa224375e82e64ae54. 

Does that still works for you ?

**Pull request merged**
