### PR TITLE
Support for Radarr, Sonarr V3 API

### PR DESCRIPTION
**Pull request by nthduy-deevotech**
## Description

Radarr has remove legacy API in the latest release https://github.com/Radarr/Radarr/releases/tag/v4.0.4.5922,
This PR support the new V3 api endpoints and added an optional attribute in `config.yml` for users with old version of Radarr can still use the application 

https://github.com/bastienwirtz/homer/issues/327

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] I've read & comply with the [contributing guidelines](https://github.com/bastienwirtz/homer/blob/main/CONTRIBUTING.md)
- [x] I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers. 
- [x] I have made corresponding changes to the documentation (README.md).
- [x] I've checked my modifications for any breaking changes, especially in the `config.yml` file

### CODE REVIEW

**Comment by crwallace2** [comment]
Based off my testing when I made similar changes for the Radarr service, the v3 queue endpoint does not function the same way as legacy, and the method used to count the items in the queue will not work.  The API now returns one top level record with an item in it named records that lists the individual items in queue.  take a look at PR#366 to see how I handled the updated queue endpoint for counting.    Unfortunately the same method of counting cannot be used in both the old and new API versions as the structure has been completely changed

**Comment by nthduy-deevotech** [comment]
Thank you @crwallace2, i've updated my code for sonarr too 👍.  Tested queue count with the lastest version of sonarr and radarr

**Comment by crwallace2** [comment]
One more minor issue, looks like you may have copied the Sonarr syntax for the legacy Radarr queue count (references series instead of movie)

          if (this.item.legacyApi) {
            for (var i = 0; i < queue.length; i++) {
              if (queue[i].series) {
                this.activity++;

**Comment by nthduy-deevotech** [comment]
Oopsie, i messed up that part, thank you for pointing that out. It should be good now !

**Comment by crwallace2** [comment]
I cloned and built the updated package and am running it in my docker config. both Sonarr and Radarr are working after the updates 

Fixes #327

**Pull request merged**
