### PR TITLE
added HELM charts

### PR DESCRIPTION
**Pull request by replicadse**
I chose to use homer on one of my k8s clusters as services grow and I keep forgetting all the Traefik IngressRoutes. Anyway, since I manage everything through ArgoCD I chose to install this app via HELM. For this, I built a few HELM charts in order to do so.
If this is interesting for you in this project, that's great. Otherwise feel free to discard this PR.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] I've read & comply with the [contributing guidelines](https://github.com/bastienwirtz/homer/blob/main/CONTRIBUTING.md)
- [x] I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [x] I have made corresponding changes to the documentation (README.md).
- [x] I've checked my modifications for any breaking changes, especially in the config.yml file

### CODE REVIEW

**Comment by alexdresko** [comment]
I'm having trouble finding a good helm chart to use since the k8s-at-home chart was removed. It would be great if there was an official chart.

**Comment by bastienwirtz** [comment]
Hi there, 
Thanks for contributing! I understand how this can be useful, but I'm think it would be better to keep it out of the official repo. There is many ways to configure & deploy homer, and if I would add all possible configuration it would be a lot. 
The thing is, if it's part of the official repo it have to be documented & maintained (kept up to date and tested for each release), and I will not be able to do that. 
@replicadse If you want you can keep it on a repo on your github and I will be happy to add a link in Homer doc to your repo. What do you think ?

**Comment by replicadse** [comment]
@bastienwirtz I can help with achieving this (this first pass probably misses some things) but realistically I won't be able to maintain it.
When it comes to the ways of installation I can totally see your point although I see it a bit different. For me and many people I know, HELM is the defacto standard for installing applications in my / our clusters so I think it should be part of the main repo - nevertheless it's just an opinion.

**Comment by bastienwirtz** [comment]
Of course. 
I agree on Helm being the standard, but I'm really not comfortable adding element that i will not be able to maintain in the repo.
I prefer closing this PR for now but it will remain searchable and useful, anyone looking for helm chart can use this PR as a base. 

If anyone is willing to write a blog post or keep it on a separate repo, I'll be happy to link it from the documentation. 
Thanks again for your contribution @replicadse.

**Comment by replicadse** [comment]
👍🏽 thanks @bastienwirtz

**Pull request closed without merging**
