### PR TITLE
Create AdGuard Home service

### PR DESCRIPTION
**Pull request by simonporte**
## Description

Create an AdGuard Home service based on the one done for Pi-Hole, which displays the status of the protection.

AdGuard Home is the main alternative to Pi-Hole:
- Open Source
- Same functionalities
- But supports conditional filters (AdBlock lists), not only host lists like PiHole

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] I've read & comply with the [contributing guidelines](https://github.com/bastienwirtz/homer/blob/master/CONTRIBUTING.md)
- [x] I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers. 
- [ ] I have made corresponding changes the documentation (README.md).
- [x] I've checked my modifications for any breaking changes, especially in the `config.yml` file

## Comments on the code

It is a copy paste of PiHole service with as few edits as possible, only 3 lines are changed.
URL is [/control/status](/control/status).
The `protection_enabled` key returns a true of false value.
I have zero knowledge of vuejs, so I had a hard time figuring why the class was not applied.
I used v-bind:class with ternary expression to be able to use a value other than the boolean returned wich was not applied.
Maybe it is not the best way to do this.

Below comparison of results showing behaviour for PiHole and AdGuard Home side by side.

### Enabled

msedge_GzDGgKbWYz

### Disabled

msedge_wj0kQd7fXZ

### Code changes

notepad++_kKWc0ccT0I

Ideas for enhancement: adding the ability to change the text from true/false to enabled/disabled.

### CODE REVIEW

**Review by bastienwirtz — COMMENTED** [review]
Thanks for starting to grow the custom services collection @simonporte! It looks good, I'll test it quickly asap & merge it if all good.

**Comment by bastienwirtz** [comment]
@simonporte didn't know about AdGuard btw, do you use it instead of PiHole or both at the same time?

**Comment by simonporte** [comment]
I'm currently testing both solutions on similar situations.
Not at the same time, because they serve the same purpose.
I was never really statisfied by pihole and ditched it long ago.
As I'm testing AdGuard Home, I give Pihole a second chance too.
My main use case is blocking ads on smartphones and TVs where adblock/ublock is not an option.

By the way, the query to AdGuard Home should only work if there is no authentication on the webui (contrary to pihole).
Any plan to support authentication at one point ?

**Review by bastienwirtz — APPROVED** [review]
Looks good :+1: 
I might find a way to factorize some code in the future but that fine for now. Thanks for the detailed PR description, appreciated.

**Comment by bastienwirtz** [comment]
@simonporte Thanks for the feedback. Authentication on specific service would have to be implemented in each custom service card. Additional properties can be added to the service item in the `config.yaml` (like api keys) if necessary.

**Pull request merged**
