### PR TITLE
Replaced darkhttpd with lighttpd

### LINKED ISSUE #162: Request Entity Too Large
I've been randomly getting a strange error in Firefox

> Request Entity Too Large
> Your request was dropped because it was too long. 
> Generated by darkhttpd/1.12 on Tue, 17 Nov 2020 16:23:40 GMT 

It seems to just arise out-of-the-blue, without any recent changes having been made and when it's been working just fine moments before! Clearing the browser cache seems to fix it, but it's annoying :) 

Has anyone else experienced this? Thanks!

### LINKED ISSUE #309: Request Entity Too Large
every day i had this problem "Request Entity Too Large". any chance to fix it?

image

### PR DESCRIPTION
**Pull request by Kirmy34**
## Description

Replace darkhttpd web server with the a bit more capable lighttpd webserver.

Fixes #309
Fixes #162 

## Type of change
This fixes an issue with darkhttpd and large cookies that would cause an "Entity too large" error.

Since it's a web server change it should't break any code, although I did not do any extensive testing. However my existing config.yml and docker compose files worked flawlessly without any further modifications.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] I've read & comply with the [contributing guidelines](https://github.com/bastienwirtz/homer/blob/main/CONTRIBUTING.md)
- [ ] I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers. 
- [ ] I have made corresponding changes to the documentation (README.md).
- [ ] I've checked my modifications for any breaking changes, especially in the `config.yml` file

### CODE REVIEW

**Comment by bastienwirtz** [comment]
Hey @Kirmy34 ! 
Thanks for your contribution ! I think it's definitely a great move to get away from `darkhttpd`, and `lighttpd` seems like a good option. I'll test that asap and get back to you.

**Comment by C4rlit0** [comment]
Hey @bastienwirtz when do you think you'll merge this fix ? No pressure, just to know :) 
Thx for your work dude!

**Comment by bastienwirtz** [comment]
Hey @Kirmy34, 

I'm going to do a couples of other modification to the docker file, so I'm merging this in a branch to test & ship everything at once. I'll keep you posted when it will be merged on master.

**Comment by Kirmy34** [comment]
Sounds good,

Let me know if you have any questions or I can help you out in any way

**Comment by C4rlit0** [comment]
Hey @Kirmy34 and @bastienwirtz 

I always get the "431 Request Header Feilds Too Large" error message that occurs even with lighttpd, I use Azure Active Directory SSO for my dashboard authentication, any ideas?

**Pull request merged**
