### PR TITLE
fix: Update Mealie service component endpoints

### LINKED ISSUE #721: Mealie Custom Service is not working
**Describe the bug**
Mealie Custom Service is not working, Homer does not connect to the API. 

**Expected behavior**
Should show the number of recipes Mealie is keeping organized or the planned meal for today if one is planned

**Logs & errors**
I suspect that is s due to the URLs of the API are not properly set in the file src/components/services/Mealie.vue
For example at line 47 is calling /api/meal-plans/today/ but if we look at the mealie [API documentation ](https://nightly.mealie.io/api/redoc/)the URL is api/groups/mealplans/today

**Screenshots**

**Configuration**
My yml for mealie is:
 `  - name: "Applications"
    icon: "fas fa-cloud"
    items:
      - name: "Mealie"
        logo: "assets/icons/mealie.png"
        type: "Mealie"
        keywords: "self hosted recipe manager "
        url: "http://10.10.1.102:9000"
        target: "_blank" # optional html a tag target attribute
        apikey: "XXXX"`

```

### PR DESCRIPTION
**Pull request by bobonthenet**
## Description

The endpoints used in the Mealie service component were incorrect and have been updated.

Fixes #721 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] I've read & comply with the [contributing guidelines](https://github.com/bastienwirtz/homer/blob/main/CONTRIBUTING.md)
- [x] I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers. 
- [x] I have made corresponding changes to the documentation (README.md).
- [x] I've checked my modifications for any breaking changes, especially in the `config.yml` file

### CODE REVIEW

**Review by AlexanderEDavis — APPROVED** [review]

**Comment by rhardih** [comment]
I ran into this issue today. Would love to see this merged and released.

**Comment by rhardih** [comment]
@bobonthenet did this fix the issue for you? I'm seeing an exception still. I think the data might not adhere to the expected format anymore, despite hitting the right endpoint now:

```
index-ttry7KsC.js:14 TypeError: Cannot read properties of undefined (reading 'recipe')
    at Mealie-BXsIlQtJ.js:1:926
    at n (index-ttry7KsC.js:14:2156)
    at Us (index-ttry7KsC.js:14:7270)
    at Proxy.ep (index-ttry7KsC.js:148:18491)
    at $i (index-ttry7KsC.js:14:29872)
    at Xo.L [as fn] (index-ttry7KsC.js:14:21807)
    at Xo.run (index-ttry7KsC.js:10:1665)
    at Xo.runIfDirty (index-ttry7KsC.js:10:1975)
    at tn (index-ttry7KsC.js:14:46)
    at bl (index-ttry7KsC.js:14:1796)
```

The response from the statistics endpoint look like this now:

```json
{
    "totalRecipes": 95,
    "totalUsers": 2,
    "totalGroups": 1,
    "uncategorizedRecipes": 22,
    "untaggedRecipes": 1
}
```

**Comment by rhardih** [comment]
Sorry the above was a red herring, I think it's the request to the `/api/groups/mealplans/today` endpoint. It can be an empty array, but there's no empty check here: https://github.com/bastienwirtz/homer/blob/main/src/components/services/Mealie.vue#L9

I don't have a working dev environment for homer at the moment, but might give it a try for a fix.

**Comment by rhardih** [comment]
Here's a new PR with the fix:

https://github.com/bastienwirtz/homer/pull/819

**Pull request merged**
