### PR TITLE
Add  Ping services

### PR DESCRIPTION
**Pull request by stubbfel**
## Description

This feature is inspired by the PiHole service.
The new service (type) check evaluate if the given url is available or not.
If the service is available then the service set the status to enable otherwise to disabled.

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] I've read & comply with the [contributing guidelines](https://github.com/bastienwirtz/homer/blob/main/CONTRIBUTING.md)
- [x] I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers. 
- [ ] I have made corresponding changes the documentation (README.md).
- [x] I've checked my modifications for any breaking changes, especially in the `config.yml` file

### CODE REVIEW

**Comment by Doc0160** [comment]
+1

**Comment by bastienwirtz** [comment]
Hi @stubbfel, thanks for your contribution! 
This is a good idea, thanks :+1:

**Comment by bastienwirtz** [comment]
@stubbfel Yeah it only works for things on the same domain or serving the right cors header, but I thinks it's kind of out of homer scope after that. BUT it would be great to add the CORS-Proxy as a solution to CORS issue in the documentation (md files in this repo). If you are willing to do so,  go for it!
The CORS issue impact other custom service as well, as people often split their service on different domain.

**Comment by JorgeAnzola** [comment]
Sorry to revive this, guys, but how could I enable this feature on my services? :D

**Pull request merged**
