### PR TITLE
add url prefix with doc

### LINKED ISSUE #290: [FR] Add URL prefix
Hey,
is there any possibility to add a URL prefix for running homer behind a reverse-proxy with a given URL eg.

example.com/dashboard

I tried it with traefik but had no luck. Got a 404 or a blank page (without and with prefix-stripping).
I looked up the source and found some occurences of BASE_URL environment variable.
Could this be a solution?

Thanks

### PR DESCRIPTION
**Pull request by mad73923**
## Description

Add URL prefix capabilities for reverse proxy applications

Fixes #290 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] I've read & comply with the [contributing guidelines](https://github.com/bastienwirtz/homer/blob/main/CONTRIBUTING.md)
- [x] I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers. 
- [x] I have made corresponding changes the documentation (README.md).
- [x] I've checked my modifications for any breaking changes, especially in the `config.yml` file

### CODE REVIEW

**Comment by mad73923** [comment]
similar to #238

**Comment by fbartels** [comment]
Homer works just fine from a subfolder even without your change. The linked pr also only changes the subfolder for the container.

**Comment by mad73923** [comment]
sure it does. but I couldn't find a other way to achieve this inside a container. The linked PR is working for docker, but only for that.
There might be folks out there running homer locally behind a reverse proxy.

This solution covers both, containerized AND local deployment.

**Comment by fbartels** [comment]
> This solution covers both, containerized AND local deployment.

That may be true, but you change is only really relevant when compiling Homer yourself and even if you don't, you could still move the build result in any directory that you want afterwards.

**Comment by mad73923** [comment]
Firstly, homer gets compiled every time it is deployed in a container. Why not using the move functionality in this step?
Secondly, moving things inside a container manually is a bad way to deploy! You'd have to do this with every update / deployment again and again.
Additionally, this change doesn't change anything to the legacy users. Only if the environment variable is set, things will change.

**Comment by bastienwirtz** [comment]
@fbartels In docker, the subdirectory will not work because If you set a subpath on your reverse proxy, Homer will not be aware of it and try to requests the the resources on `/`.

@mad73923 I like the idea, and this is more elegant than the #238 solution, but it works only if you build the docker image yourself right? If you pull it from dockerhub (like most peolple do), the subfolder env var will not be taken into account. In #238, it works without image rebuild. 

That being said, maybe the best solution would be to add a `proxy_path` or `homer_path` or something like that in the `config.yml` configuration and prefix resources requests with it. And for the hosting, leave it to the vhost or proxy configuration (so no modification necessary on the build path).

What do you think @mad73923 @boerniee @fbartels ?

**Comment by boerniee** [comment]
Yes, this one is more elegant, but it doesnt work for pulled images from Dockerhub. As you @bastienwirtz mentioned, I also think the most users will do this.
For people which host homer locally, the effect of building the project and being placed in the right dir automatically, or downloading the prebuild project and placing it manually in the right location, is the same. Here I also think the most people will download the prebuild project. In my opinion there is no need to change anything for people who locally host homer, because instead of placing it in the www-root they can move it into another folder.

Another thing I would like to mention is, that I like the idea of maintaining the subfolder config in the docker labels side by side with the reverse-proxy configuration for that container.
Maybe this thing could be solved by doing some darkhttp config?

**Comment by mad73923** [comment]
Hey @bastienwirtz and @boerniee ,
you're right. The container will already be compiled when pulling. I forgot about that.
Unfortunately, after a quick glimpse at darkhttp, ther's no prefix parameter available.
Do you have any better ideas?

**Comment by mad73923** [comment]
since this feature was implemented in #238 i close this PR

**Pull request closed without merging**
